// frontend/src/pages/FinalReview.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import Navbar from '../components/Navbar';
import Button from '../components/Button';
import Loader from '../components/Loader';
import ContentPanel from '../components/ContentPanel';
import { useAuth } from '../context/AuthContext';
import axios from 'axios';

const FinalReview = () => {
  const { token } = useAuth();
  const navigate = useNavigate();

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [summary, setSummary] = useState(null);
  const [activeView, setActiveView] = useState('content');
  // 'content' | 'factsheet' | 'review'

  useEffect(() => {
    const id = localStorage.getItem('campaign_id');
    if (!id) { navigate('/upload'); return; }
    fetchSummary(id);
  }, []);

  const fetchSummary = async (campaignId) => {
    setLoading(true);
    try {
      const response = await axios.get(
        `http://localhost:5000/api/campaign/${campaignId}/summary`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setSummary(response.data);
    } catch (err) {
      setError('Failed to load campaign summary.');
    } finally {
      setLoading(false);
    }
  };

  // ─── Copy to Clipboard ───────────────────────────────────────────
  const copyToClipboard = (text, label) => {
    navigator.clipboard.writeText(text).then(() => {
      alert(`✅ ${label} copied to clipboard!`);
    });
  };

  // ─── Export Full Campaign Kit ────────────────────────────────────
  const exportCampaignKit = () => {
    if (!summary?.content) return;

    const { blog, social, email } = summary.content;
    const campaign = summary.campaign;
    const fact_sheet = summary.fact_sheet;

    const kit = `
═══════════════════════════════════════════════════════════
  AUTONOMOUS CONTENT FACTORY — CAMPAIGN KIT
═══════════════════════════════════════════════════════════
Campaign: ${campaign?.title || 'Untitled'}
Source:   ${campaign?.source_name || 'Unknown'}
Date:     ${new Date(campaign?.created_at).toLocaleDateString()}
Status:   ${campaign?.status?.toUpperCase()}

───────────────────────────────────────────────────────────
  FACT SHEET (Source of Truth)
───────────────────────────────────────────────────────────
Product:          ${fact_sheet?.product_or_topic || 'N/A'}
Company:          ${fact_sheet?.company_or_brand || 'N/A'}
Value Prop:       ${fact_sheet?.value_proposition || 'N/A'}
Core Features:    ${fact_sheet?.core_features?.join(', ') || 'N/A'}
Target Audience:  ${fact_sheet?.target_audience?.join(', ') || 'N/A'}

───────────────────────────────────────────────────────────
  BLOG POST
───────────────────────────────────────────────────────────
Title: ${blog?.title || 'N/A'}

${blog?.content || 'No content'}

───────────────────────────────────────────────────────────
  SOCIAL MEDIA THREAD
───────────────────────────────────────────────────────────
${social?.posts?.map(p => `[${p.number}/5] ${p.content}`).join('\n\n') || 'No content'}

───────────────────────────────────────────────────────────
  EMAIL TEASER
───────────────────────────────────────────────────────────
Subject: ${email?.subject_line || 'N/A'}

${email?.content || 'No content'}

═══════════════════════════════════════════════════════════
  Generated by Autonomous Content Factory
═══════════════════════════════════════════════════════════
`.trim();

    // Download as .txt file
    const blob = new Blob([kit], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `campaign-kit-${summary.campaign?.id?.slice(0, 8) || 'export'}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // ─── Render Fact Sheet ───────────────────────────────────────────
  const renderFactSheet = () => {
    const fs = summary?.fact_sheet;
    if (!fs) return null;

    const sections = [
      { title: '🏷️ Product / Topic', content: fs.product_or_topic || 'N/A' },
      { title: '🏢 Company / Brand', content: fs.company_or_brand || 'N/A' },
      { title: '💡 Value Proposition', content: fs.value_proposition || 'N/A' },
      { title: '⚡ Core Features', content: fs.core_features?.length ? fs.core_features : ['None'] },
      { title: '🎯 Target Audience', content: fs.target_audience?.length ? fs.target_audience : ['None'] },
      { title: '📊 Key Statistics', content: fs.key_statistics?.length ? fs.key_statistics : ['None'] },
      { title: '💰 Pricing', content: fs.pricing?.plans?.length ? fs.pricing.plans.map(p => `${p.name}: ${p.price}`) : ['No pricing'] },
      { title: '📅 Launch Date', content: fs.launch_date || 'N/A' },
    ];

    return (
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
        gap: '1rem'
      }}>
        {sections.map((section, i) => (
          <div key={i} className="glass-card" style={{ padding: '1rem' }}>
            <p style={{
              color: 'var(--text-muted)', fontSize: '0.75rem',
              fontWeight: 600, textTransform: 'uppercase',
              letterSpacing: '0.05em', marginBottom: '0.5rem'
            }}>
              {section.title}
            </p>
            {Array.isArray(section.content) ? (
              <ul style={{
                paddingLeft: '1rem', margin: 0,
                display: 'flex', flexDirection: 'column', gap: '4px'
              }}>
                {section.content.map((item, j) => (
                  <li key={j} style={{
                    color: 'var(--text-secondary)',
                    fontSize: '0.88rem', lineHeight: 1.5
                  }}>{item}</li>
                ))}
              </ul>
            ) : (
              <p style={{
                color: 'var(--text-secondary)',
                fontSize: '0.88rem', lineHeight: 1.5, margin: 0
              }}>
                {section.content}
              </p>
            )}
          </div>
        ))}
      </div>
    );
  };

  // ─── Render Editor Review ────────────────────────────────────────
  const renderEditorReview = () => {
    const fb = summary?.feedback;
    if (!fb) return (
      <div style={{
        textAlign: 'center', padding: '2rem',
        color: 'var(--text-muted)'
      }}>
        No editor feedback available for this campaign.
      </div>
    );

    const items = [
      {
        label: '📝 Blog Post',
        approved: fb.blog_approved,
        notes: fb.blog_notes,
        color: '#7c3aed'
      },
      {
        label: '📱 Social Thread',
        approved: fb.social_approved,
        notes: fb.social_notes,
        color: '#3b82f6'
      },
      {
        label: '📧 Email Teaser',
        approved: fb.email_approved,
        notes: fb.email_notes,
        color: '#06b6d4'
      },
    ];

    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        {items.map(({ label, approved, notes, color }) => (
          <div key={label} className="glass-card" style={{ padding: '1.2rem' }}>
            <div style={{
              display: 'flex', alignItems: 'center',
              justifyContent: 'space-between', marginBottom: notes ? '0.8rem' : 0
            }}>
              <span style={{
                color: 'var(--text-primary)',
                fontWeight: 700, fontSize: '0.95rem'
              }}>
                {label}
              </span>
              <div style={{
                background: approved
                  ? 'rgba(34,197,94,0.1)'
                  : 'rgba(239,68,68,0.1)',
                border: `1px solid ${approved
                  ? 'rgba(34,197,94,0.3)'
                  : 'rgba(239,68,68,0.3)'}`,
                borderRadius: '20px', padding: '3px 12px',
                fontSize: '0.8rem',
                color: approved ? '#4ade80' : '#f87171',
                fontWeight: 600
              }}>
                {approved ? '✅ Approved' : '❌ Needs Review'}
              </div>
            </div>
            {notes && (
              <p style={{
                color: 'var(--text-secondary)',
                fontSize: '0.88rem', lineHeight: 1.6,
                margin: 0,
                padding: '0.6rem',
                background: 'var(--bg-secondary)',
                borderRadius: 'var(--radius-sm)'
              }}>
                {notes}
              </p>
            )}
          </div>
        ))}
      </div>
    );
  };

  // ─── Main Render ─────────────────────────────────────────────────
  if (loading) {
    return (
      <div style={{ minHeight: '100vh', background: 'var(--bg-primary)' }}>
        <Navbar />
        <div style={{
          display: 'flex', alignItems: 'center',
          justifyContent: 'center', minHeight: '70vh'
        }}>
          <Loader text="Loading campaign summary..." />
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div style={{ minHeight: '100vh', background: 'var(--bg-primary)' }}>
        <Navbar />
        <div style={{
          maxWidth: 600, margin: '4rem auto',
          padding: '1.5rem', textAlign: 'center'
        }}>
          <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>❌</div>
          <p style={{ color: '#f87171', marginBottom: '1.5rem' }}>{error}</p>
          <Button onClick={() => navigate('/agent-room')}>← Back to Agent Room</Button>
        </div>
      </div>
    );
  }

  const allApproved = summary?.feedback
    ? (summary.feedback.blog_approved &&
       summary.feedback.social_approved &&
       summary.feedback.email_approved)
    : false;

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg-primary)' }}>
      <Navbar />

      <div style={{ maxWidth: 1100, margin: '0 auto', padding: '2.5rem 1.5rem' }}>

        {/* Header */}
        <div style={{
          display: 'flex', alignItems: 'flex-start',
          justifyContent: 'space-between',
          marginBottom: '2rem', flexWrap: 'wrap', gap: '1rem'
        }}>
          <div>
            <div style={{
              display: 'inline-flex', alignItems: 'center', gap: '0.5rem',
              background: 'rgba(124,58,237,0.15)',
              border: '1px solid var(--border-accent)',
              borderRadius: '20px', padding: '0.3rem 1rem',
              marginBottom: '0.8rem'
            }}>
              <span style={{
                fontSize: '0.75rem',
                color: 'var(--accent-purple)', fontWeight: 600
              }}>
                FINAL REVIEW
              </span>
            </div>
            <h1 style={{
              fontSize: '1.8rem', fontWeight: 800,
              color: 'var(--text-primary)', marginBottom: '0.4rem'
            }}>
              {summary?.campaign?.title || 'Campaign Review'}
            </h1>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.95rem' }}>
              Source: {summary?.campaign?.source_name} ·
              Version {summary?.content?.version || 1}
            </p>
          </div>

          {/* Action Buttons */}
          <div style={{ display: 'flex', gap: '0.8rem', flexWrap: 'wrap' }}>
            <Button
              onClick={() => copyToClipboard(
                [
                  summary?.content?.blog?.content,
                  summary?.content?.social?.posts?.map(p => p.content).join('\n\n'),
                  summary?.content?.email?.content
                ].filter(Boolean).join('\n\n---\n\n'),
                'Full Campaign Kit'
              )}
              variant="outline"
              size="md"
            >
              📋 Copy All
            </Button>
            <Button onClick={exportCampaignKit} size="md">
              ⬇️ Export Kit
            </Button>
            <Button
              onClick={() => navigate('/dashboard')}
              variant="ghost"
              size="md"
            >
              📁 Dashboard
            </Button>
          </div>
        </div>

        {/* Overall Status Banner */}
        <div style={{
          background: allApproved
            ? 'rgba(34,197,94,0.08)'
            : 'rgba(245,158,11,0.08)',
          border: `1px solid ${allApproved
            ? 'rgba(34,197,94,0.25)'
            : 'rgba(245,158,11,0.25)'}`,
          borderRadius: 'var(--radius-md)',
          padding: '1.2rem 1.5rem',
          marginBottom: '2rem',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          flexWrap: 'wrap', gap: '1rem'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
            <span style={{ fontSize: '1.8rem' }}>
              {allApproved ? '🎉' : '⚠️'}
            </span>
            <div>
              <p style={{
                color: allApproved ? '#4ade80' : '#fbbf24',
                fontWeight: 700, fontSize: '1rem', margin: 0
              }}>
                {allApproved
                  ? 'Campaign Fully Approved — Ready to Publish!'
                  : 'Campaign Complete — Some Content May Need Review'}
              </p>
              <p style={{
                color: 'var(--text-muted)',
                fontSize: '0.85rem', margin: '2px 0 0'
              }}>
                3 agents processed your content through the quality pipeline
              </p>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '0.8rem' }}>
            {[
              { label: 'Blog', approved: summary?.feedback?.blog_approved },
              { label: 'Social', approved: summary?.feedback?.social_approved },
              { label: 'Email', approved: summary?.feedback?.email_approved },
            ].map(({ label, approved }) => (
              <div key={label} style={{
                background: approved
                  ? 'rgba(34,197,94,0.15)'
                  : 'rgba(239,68,68,0.15)',
                border: `1px solid ${approved
                  ? 'rgba(34,197,94,0.3)'
                  : 'rgba(239,68,68,0.3)'}`,
                borderRadius: '20px', padding: '4px 12px',
                fontSize: '0.78rem',
                color: approved ? '#4ade80' : '#f87171',
                fontWeight: 600
              }}>
                {approved ? '✅' : '⚠️'} {label}
              </div>
            ))}
          </div>
        </div>

        {/* View Toggle */}
        <div style={{
          display: 'flex', gap: '0.5rem',
          background: 'var(--bg-secondary)',
          borderRadius: 'var(--radius-sm)',
          padding: '4px', marginBottom: '2rem',
          width: 'fit-content'
        }}>
          {[
            { id: 'content', label: '✍️ Content' },
            { id: 'factsheet', label: '🔒 Fact Sheet' },
            { id: 'review', label: '✅ Editor Review' },
          ].map(view => (
            <button key={view.id}
              onClick={() => setActiveView(view.id)}
              style={{
                padding: '0.6rem 1.2rem',
                borderRadius: '6px', border: 'none',
                background: activeView === view.id
                  ? 'var(--gradient-main)'
                  : 'transparent',
                color: activeView === view.id
                  ? 'white'
                  : 'var(--text-secondary)',
                fontWeight: 600, cursor: 'pointer',
                fontSize: '0.88rem',
                fontFamily: 'var(--font-main)',
                transition: 'all 0.2s'
              }}>
              {view.label}
            </button>
          ))}
        </div>

        {/* View Content */}
        {activeView === 'content' && summary?.content && (
          <div>
            {/* Per-content copy buttons */}
            <div style={{
              display: 'flex', gap: '0.6rem',
              marginBottom: '1rem', flexWrap: 'wrap'
            }}>
              <button
                onClick={() => copyToClipboard(
                  summary.content.blog?.content || '',
                  'Blog Post'
                )}
                style={{
                  background: 'var(--glass-bg)',
                  border: '1px solid var(--glass-border)',
                  borderRadius: '20px', padding: '4px 14px',
                  fontSize: '0.8rem', color: '#7c3aed',
                  fontWeight: 600, cursor: 'pointer',
                  fontFamily: 'var(--font-main)'
                }}>
                📋 Copy Blog
              </button>
              <button
                onClick={() => copyToClipboard(
                  summary.content.social?.posts?.map(p => p.content).join('\n\n') || '',
                  'Social Thread'
                )}
                style={{
                  background: 'var(--glass-bg)',
                  border: '1px solid var(--glass-border)',
                  borderRadius: '20px', padding: '4px 14px',
                  fontSize: '0.8rem', color: '#3b82f6',
                  fontWeight: 600, cursor: 'pointer',
                  fontFamily: 'var(--font-main)'
                }}>
                📋 Copy Social
              </button>
              <button
                onClick={() => copyToClipboard(
                  `Subject: ${summary.content.email?.subject_line}\n\n${summary.content.email?.content}` || '',
                  'Email Teaser'
                )}
                style={{
                  background: 'var(--glass-bg)',
                  border: '1px solid var(--glass-border)',
                  borderRadius: '20px', padding: '4px 14px',
                  fontSize: '0.8rem', color: '#06b6d4',
                  fontWeight: 600, cursor: 'pointer',
                  fontFamily: 'var(--font-main)'
                }}>
                📋 Copy Email
              </button>
            </div>

            <ContentPanel
              blog={summary.content.blog}
              social={summary.content.social}
              email={summary.content.email}
            />
          </div>
        )}

        {activeView === 'factsheet' && renderFactSheet()}
        {activeView === 'review' && renderEditorReview()}

        {/* Bottom Navigation */}
        <div style={{
          display: 'flex', gap: '1rem',
          marginTop: '3rem', paddingTop: '1.5rem',
          borderTop: '1px solid var(--border-subtle)',
          flexWrap: 'wrap'
        }}>
          <Button
            onClick={() => navigate('/agent-room')}
            variant="ghost"
            size="md"
          >
            ← Back to Agent Room
          </Button>
          <Button
            onClick={() => navigate('/dashboard')}
            variant="outline"
            size="md"
          >
            📁 All Campaigns
          </Button>
          <Button onClick={handleNewCampaign} size="md">
            ⚡ New Campaign
          </Button>
        </div>
      </div>
    </div>
  );

  function handleNewCampaign() {
    localStorage.removeItem('campaign_id');
    localStorage.removeItem('campaignSource');
    navigate('/upload');
  }
};

export default FinalReview;